# Generated by Django 4.0.1 on 2022-01-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=250)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("B", "Basic"),
                            ("I", "Intermediary"),
                            ("A", "Advanced"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
