# Generated by Django 4.0.1 on 2022-01-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_course_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
    ]
