name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make
      
    - name: Install devs dependences
      run: make install-deps-dev
      
    - name: Run check
      run: make analitcs
